### ISSUE TITLE
Several typos in ses_dll.py

### ISSUE THREAD

**Issue by fuzhenxiao** [bzwartsenberg/SESWrapper#1]
In line 277,287,297,307,317,327 several  ","  are missing
should be `funcparams = ((1,'binding_energy),)` instead of `funcparams = ((1,'binding_energy))`. This causes param error.

In line 351 `WRP_ElementVoltage` should be `WRP_SetElementVoltage`. This maybe because the official API has updated. I'm using SESwrapper 2.2.7  in which there is no "WRP_ElementVoltage"

**Comment by bzwartsenberg** [comment]
Thank you for pointing that out! I'll have a look. Which Python version are you running? So far no issues have come up for me with the tuples (although you are right they are not defined correctly). 

As for the ElementVoltage that was indeed the wrong function. I will add a readme file explaining what SESwrapper version this was tested on too (2.7.4)

Edit: Both issues were present for me as well, I'm updating it now. Thanks for flagging.
